server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Mani@1489
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  zipkin:
    baseUrl: http://${ZIPKIN_SERVER_URL:localhost}:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
      
logging:
  file:
    name: productservice.log
    
management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace
  endpoint:
    health:
      enabled: true
      show-details: always

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}