server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: Mani@1489
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  zipkin:
    baseUrl: http://${ZIPKIN_SERVER_URL:localhost}:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
    
    
logging:
  file:
    name: paymentservice.log
    
management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httptrace
  endpoint:
    health:
      enabled: true
      show-details: always